
#---------------- GUI -------------------------
JLABEL_FILTER_INFO=Filter
JBUTTON_CLEAN_FILTER=Clean
JMENU_VNC_ACCESS=VNC Access
JMENU_COMPUTER=Computer
JMENUITEM_COMPUTER_CREATE=Create
JMENUITEM_VNC_OPEN_SCREEN_TO_CONNECTION=Open VNC Access screen
TITLE=Computers List