CREATE_COMPUTER_COMPUTER_ALREADY_EXIST_EXCEPTION=Um computador com o nome: %s, e IP: %s, já existe. As informações já existentes foram atualizadas
UNEXPECTED_ERROR_EXCEPTION=Um erro inesperado ocorreu
FIND_BY_ID_NOT_FOUND_EXCEPTION=Nenhum computador com o ID %d foi encontrado no banco de dados