CREATE_COMPUTER_LIST_EXCEPTION=Não foi possível criar a lista de computadores
UPDATE_COMPUTER_EXCEPTION=Não foi possível atualizar o computador
DELETE_COMPUTER_EXCEPTION=Não foi possível excluir o computador
CREATE_COMPUTER_EXCEPTION=Não foi possível criar o computador