# the configuration file

# the execution mode, valid values (NORMAL or DEMO)
EXECUTION_MODE=DEMO

# the enviroment mode, valid values (PRODUCTION or TEST)
ENVIRONMENT_MODE=TEST

# the storage option, valid value (SQL_SERVER or H2)
STORAGE=H2

# the authentication mode, valid values (ACTIVE_DIRECTORY or PROGRAM)
AUTHENTICATION=PROGRAM

# the program language, valid values (pt_br or en_us) *lower case!
LANGUAGE=en_us