STATUS=Estado
TYPE_OF_SESSION=Tipo de sessão
USERNAME=Nome do usuário
HOSTNAME=Nome do computador
IP=IP
JAVIS_CLIENT_VERSION=Versão do Javis Cliente
DETAILS=Detalhes
OK=OK
CANCEL=Cancelar

CREATE_COMPUTER_EXCEPTION=Não é possível salvar computador
UPDATE_COMPUTER_EXCEPTION=Não é possível atualizar as informações do computador

ERROR_INVALID_INFORMATION=O Computador contém informações inválidas

CONFIRM_BEFORE_OK=Continuar com as alterações?