
POWEROFF=Power Off
POWERON=Power On

INVALID=-
CONSOLE_CONNECT=Console Connect
CONSOLE_DISCONNECT=Console Disconnect
REMOTE_CONNECT=Remote Connect
REMOTE_DISCONNECT=Remote Disconnect
SESSION_LOGON=Session LogOn
SESSION_LOGOFF=Session LogOff
SESSION_LOCK=Session Lock
SESSION_UNLOCK=Session Unlock
SESSION_REMOTE_CONTROL=Session Remote Control
SESSION_CREATE=Session Create
SESSION_TERMINATE=Session Terminate
SESSION_LIX_LOGON=Session Linux LogOn

YES=Yes
NO=No

TIME_FORMAT_PATTERN=MM/dd/yyyy hh:mm a

#---------------- exceptions messages ---------------- 
SESSION_TYPE_EXCEPTION=The value %d is not a valid value for the session type
POWERSTATUS_TYPE_EXCEPTION=The value %d is not a valid value for the computer status
JAVIS_CLIENT_VERSION_SIZE_EXCEPTION=Javis client version text cannot be longer than %d characters

INVALID_ID_EXCEPTION=ID value must be a number greater than %d

INVALID_USERNAME_EMPTY_EXCEPTION=Username cannot be empty
INVALID_USERNAME_SIZE_EXCEPTION=Username cannot be longer than %d characters

INVALID_HOSTNAME_EMPTY_EXCEPTION=Hostname cannot be empty
INVALID_HOSTNAME_SIZE_EXCEPTION=Username cannot be longer than %d characters

INVALID_DETAILS_SIZE_EXCEPTION=Username cannot be longer than %d characters