
#----------- EXCEPTION ---------------
INVALID_IP_SIZE_EXCEPTION=Text size cannot exceed %d characters
STRING_IP_SYNTAX_EXCEPTION=O IP deve ter 4 octetos de 0-255 separados por pontos: XXX.XXX.XXX.XXX