JBUTTON_CLOSE=Fechar

JLABEL_INFORMATION=<html>%s experimentou um erro não tratado, e pode estar funcionando de forma inconsistente.<br>\
É aconselhavel reinicar o programa para garantir que tudo funcione como o esperado.<br><br>\
Esse erro pode ser reportado para o desenvolvedor.<br>\
Faça o seguinte:<br>\
<i><font color=\"red\">Copie</font></i> e <i><font color=\"red\">cole</font></i> o \
texto abaixo e envie por e-mail \
<font color=\"red\">com uma breve explicação</font> do que você estava fazendo antes do erro acontecer.<br>

JLABEL_TITLE_H1=Um erro não tratado ocorreu!

JLABEL_PROGRAM_NAME_INFO=Nome do programa:
JLABEL_PROGRAM_NAME=%s

JLABEL_VERSION_INFO=Versão do programa:
JLABEL_VERSION=%s

JLABEL_THREAD_ID_INFO=ID da Thread:
JLABEL_THREAD_ID=%s

JLABEL_THREAD_NAME_INFO=Nome da Thread:
JLABEL_THREAD_NAME=%s