
POWEROFF=Desligado
POWERON=Ligado

INVALID=-
CONSOLE_CONNECT=Console Conectado
CONSOLE_DISCONNECT=Console Desconectado
REMOTE_CONNECT=Remoto (Conectado)
REMOTE_DISCONNECT=Remoto (Desconectado)
SESSION_LOGON=Entrou na Sessão
SESSION_LOGOFF=Saiu da Sessão
SESSION_LOCK=Sessão desbloqueada
SESSION_UNLOCK=Sessão bloqueada
SESSION_REMOTE_CONTROL=Sessão (Controle remoto)
SESSION_CREATE=Sessão criada
SESSION_TERMINATE=Sessão Terminada
SESSION_LIX_LOGON=Sessão (Linux Login)

YES=Sim
NO=Não

TIME_FORMAT_PATTERN=dd/MM/yyyy HH:mm

#---------------- exceptions messages ---------------- 
SESSION_TYPE_EXCEPTION=O valor %d não é um valor válido para o tipo de sessão
POWERSTATUS_TYPE_EXCEPTION=O valor %d não é um valor válido para o estado do computador
JAVIS_CLIENT_VERSION_SIZE_EXCEPTION=O texto da versão do cliente Javis não pode ter mais que %d caracteres

INVALID_ID_EXCEPTION=O valor do ID deve ser um número maior que 0

INVALID_USERNAME_EMPTY_EXCEPTION=O nome de usuário não pode estar vazio
INVALID_USERNAME_SIZE_EXCEPTION=O nome de usuário não pode ter mais de %d caracteres

INVALID_HOSTNAME_EMPTY_EXCEPTION=O nome do computador não pode estar vazio
INVALID_HOSTNAME_SIZE_EXCEPTION=O nome do usuário não pode ter mais do que %d caracteres

INVALID_DETAILS_SIZE_EXCEPTION=O nome de usuário não pode ter mais do que %d caracteres