STATUS=Status
TYPE_OF_SESSION=Type of session
USERNAME=Username
HOSTNAME=Hostname
IP=IP
JAVIS_CLIENT_VERSION=Javis Client Version
DETAILS=Details
OK=OK
CANCEL=Cancel

CREATE_COMPUTER_EXCEPTION=Unable to save computer
UPDATE_COMPUTER_EXCEPTION=Unable to update computer information

ERROR_INVALID_INFORMATION=The Computer Contains Invalid Information

CONFIRM_BEFORE_OK=Continue with changes?