
#----------------- GUI --------------------------------------------------
COLUMN_NAME_ID=ID
COLUMN_NAME_ID_POWER_STATUS_COMPUTER=Estado do computador
COLUMN_NAME_ID_SESSION_TYPE=Tipo de sessão
COLUMN_NAME_ID_USERNAME=Nome do usuário
COLUMN_NAME_ID_HOSTNAME=Nome do computador
COLUMN_NAME_ID_IP=IP
COLUMN_NAME_ID_IS_MANUAL=Informação criada manualmente?
COLUMN_NAME_ID_LOGIN_DATE=Data de Login
COLUMN_NAME_ID_JAVIS_CLIENT_VERSION=Versão do Javis Client
COLUMN_NAME_ID_DETAILS=Detalhes

JMENUITEM_VNC_ACCESS_THE_COMPUTER_ONLY_TO_VIEW=Automático (ver somente a tela)
JMENUITEM_VNC_ACCESS_THE_COMPUTER_AND_INTERACT=Automático (interagir usando mouse e teclado)
JMENUITEM_VNC_ACCESS_THE_COMPUTER_WITH_CREDENTIALS=Inserir as credenciais de acesso
JMENUITEM_COPY_CELL_CONTENT=Copiar o conteúdo da célula
JMENUITEM_COMPUTER_UPDATE=Atualizar
JMENUITEM_COMPUTER_DELETE=Excluir
JMENU_COMPUTER_OPTIONS=Computador
JMENU_VNC_CONNECTION_OPTIONS=Acessar o computador

CONFIRM_DELETION=Excluir o computador?