CREATE_COMPUTER_COMPUTER_ALREADY_EXIST_EXCEPTION=A computer with hostname: %s, and ip: %s, already exists. Existing information has been updated
UNEXPECTED_ERROR_EXCEPTION=An unexpected error occurred
FIND_BY_ID_NOT_FOUND_EXCEPTION=No computer with ID %d was found in the database