PROPERTY_NOT_FOUND_EXCEPTION=Property %s not found
PROPERTY_NOT_FOUND_EMPTY_STRING_EXCEPTION=Property %s cannot be empty
PROPERTY_NOT_FOUND_INVALID_VALUE_EXCEPTION=The value %s is invalid for property %s