
#----------------- GUI --------------------------------------------------
COLUMN_NAME_ID=ID
COLUMN_NAME_ID_POWER_STATUS_COMPUTER=Computer Status
COLUMN_NAME_ID_SESSION_TYPE=Session Type
COLUMN_NAME_ID_USERNAME=Username
COLUMN_NAME_ID_HOSTNAME=Hostname
COLUMN_NAME_ID_IP=IP
COLUMN_NAME_ID_IS_MANUAL=Manually created information?
COLUMN_NAME_ID_LOGIN_DATE=Login Date
COLUMN_NAME_ID_JAVIS_CLIENT_VERSION=Javis Client Version
COLUMN_NAME_ID_DETAILS=Details

JMENUITEM_VNC_ACCESS_THE_COMPUTER_ONLY_TO_VIEW=Automatic (see screen only)
JMENUITEM_VNC_ACCESS_THE_COMPUTER_AND_INTERACT=Automatic (interact using mouse and keyboard)
JMENUITEM_VNC_ACCESS_THE_COMPUTER_WITH_CREDENTIALS=Enter access credentials
JMENUITEM_COPY_CELL_CONTENT=Copy cell content
JMENUITEM_COMPUTER_UPDATE=Update
JMENUITEM_COMPUTER_DELETE=Delete
JMENU_COMPUTER_OPTIONS=Computer
JMENU_VNC_CONNECTION_OPTIONS=Access the computer

CONFIRM_DELETION=Delete the computer?