JBUTTON_CLOSE=Close

JLABEL_INFORMATION=<html>%s has experienced an unhandled error, and may be acting inconsistently.<br>\
It is advisable to restart the program to ensure that everything works as expected.<br><br>\
This error may be reported to the developer.<br>\
Please do the following:<br>\
<i><font color=\"red\">Copy</font></i> and <i><font color=\"red\">paste</font></i> the \
text below and email it to them \
<font color=\"red\">with a brief explanation</font> of what you were doing before the error occurred.<br>

JLABEL_TITLE_H1=An unhandled error occurred!

JLABEL_PROGRAM_NAME_INFO=Program name:
JLABEL_PROGRAM_NAME=%s

JLABEL_VERSION_INFO=Program Version:
JLABEL_VERSION=%s

JLABEL_THREAD_ID_INFO=Thread ID:
JLABEL_THREAD_ID=%s

JLABEL_THREAD_NAME_INFO=Thread name:
JLABEL_THREAD_NAME=%s