CREATE_COMPUTER_LIST_EXCEPTION=Unable to create computer list
UPDATE_COMPUTER_EXCEPTION=Unable to update the computer
DELETE_COMPUTER_EXCEPTION=Unable to delete the computer
CREATE_COMPUTER_EXCEPTION=Unable to create the computer