PROPERTY_NOT_FOUND_EXCEPTION=A propriedade %s não foi encontrada
PROPERTY_NOT_FOUND_EMPTY_STRING_EXCEPTION=A propriedade %s não pode estar vazia
PROPERTY_NOT_FOUND_INVALID_VALUE_EXCEPTION=O valor %s é inválido para a propriedade %s