
#---------------- GUI -------------------------
JLABEL_FILTER_INFO=Filtro
JBUTTON_CLEAN_FILTER=Limpar
JMENU_VNC_ACCESS=Acesso VNC
JMENU_COMPUTER=Computador
JMENUITEM_COMPUTER_CREATE=Criar
JMENUITEM_VNC_OPEN_SCREEN_TO_CONNECTION=Abrir a tela de acesso VNC
TITLE=Lista de Computadores